<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>span_Submit</name>
   <tag></tag>
   <elementGuidId>4120cc47-ee79-4edf-a33a-414bbb8d13c2</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>//*[(text() = 'Submit' or . = 'Submit')]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>wdg-button-label</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Submit</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>/html[1]/body[@class=&quot;av-form Chrome form-loaded&quot;]/form[@class=&quot;container-fluid av-optional id-AvokaSmartForm av-focus-styling mg-base mg-form av-item-container ng-pristine ng-valid ng-scope&quot;]/div[@class=&quot;container-fluid&quot;]/div[@class=&quot;row&quot;]/nav[@class=&quot;av-optional id-nav_wizard_bar nav-wizard-bar col-xs-12 col-sm-12 col-md-12 col-lg-12 av-item-container ng-scope&quot;]/div[@class=&quot;av-menu-wizard-bar container-fluid ng-scope&quot;]/div[@class=&quot;row&quot;]/div[@class=&quot;av-optional id-wizard_submit nav-wizard-button nav-wizard-submit-button col-xs-12 col-sm-12 col-md-12 col-lg-12 av-item-container ng-scope&quot;]/button[@class=&quot;btn wdg-button&quot;]/span[@class=&quot;wdg-button-label&quot;]</value>
   </webElementProperties>
</WebElementEntity>
